/* Generated By:JJTree: Do not edit this line. ANALYZE.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ANALYZE extends SimpleNode {
  public ANALYZE(int id) {
    super(id);
  }

  public ANALYZE(Scanner p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public SimpleNode jjtAccept(ScannerVisitor visitor, SimpleNode data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d2f40b3fea2b6e5405705cbe1091aad4 (do not edit this line) */
