/* Generated By:JJTree: Do not edit this line. NOHEADERS.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class NOHEADERS extends SimpleNode {
  public NOHEADERS(int id) {
    super(id);
  }

  public NOHEADERS(Scanner p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public SimpleNode jjtAccept(ScannerVisitor visitor, SimpleNode data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=62896644141f4447a7bd975912e6a610 (do not edit this line) */
