/* Generated By:JavaCC: Do not edit this line. ScannerTreeConstants.java Version 5.0 */
public interface ScannerTreeConstants
{
  public int JJTPROG = 0;
  public int JJTIMPORT = 1;
  public int JJTIMPOPTIONS = 2;
  public int JJTFLNM = 3;
  public int JJTNOHEADERS = 4;
  public int JJTMODEL = 5;
  public int JJTVOID = 6;
  public int JJTCOLRULE = 7;
  public int JJTCOLPARTRULE = 8;
  public int JJTCOLOR = 9;
  public int JJTCOLAND = 10;
  public int JJTCOLVALEXPR = 11;
  public int JJTWHERE = 12;
  public int JJTSACD = 13;
  public int JJTADD = 14;
  public int JJTMULT = 15;
  public int JJTRULE = 16;
  public int JJTPARTRULE = 17;
  public int JJTOR = 18;
  public int JJTAND = 19;
  public int JJTVALEXPR = 20;
  public int JJTCONSTRAINTS = 21;
  public int JJTSTRING = 22;
  public int JJTINTEGER = 23;
  public int JJTFLOATY = 24;
  public int JJTANALYZE = 25;
  public int JJTANLZOPTIONS = 26;
  public int JJTRULEOPT = 27;
  public int JJTROWS = 28;
  public int JJTCOLS = 29;
  public int JJTRANGE = 30;
  public int JJTIDEN = 31;


  public String[] jjtNodeName = {
    "PROG",
    "IMPORT",
    "IMPOPTIONS",
    "FLNM",
    "NOHEADERS",
    "MODEL",
    "void",
    "COLRULE",
    "COLPARTRULE",
    "COLOR",
    "COLAND",
    "COLVALEXPR",
    "WHERE",
    "SACD",
    "ADD",
    "MULT",
    "RULE",
    "PARTRULE",
    "OR",
    "AND",
    "VALEXPR",
    "CONSTRAINTS",
    "STRING",
    "INTEGER",
    "FLOATY",
    "ANALYZE",
    "ANLZOPTIONS",
    "RULEOPT",
    "ROWS",
    "COLS",
    "RANGE",
    "IDEN",
  };
}
/* JavaCC - OriginalChecksum=317acda8d6df782135f4f99b43d29d89 (do not edit this line) */
