/* Generated By:JJTree: Do not edit this line. ANLZOPTIONS.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ANLZOPTIONS extends SimpleNode {
  public ANLZOPTIONS(int id) {
    super(id);
  }

  public ANLZOPTIONS(Scanner p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public SimpleNode jjtAccept(ScannerVisitor visitor, SimpleNode data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6caaebc1e8edc4dfa8e587f3c43e0050 (do not edit this line) */
