/* Generated By:JJTree: Do not edit this line. COLVALEXPR.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class COLVALEXPR extends SimpleNode {
  public COLVALEXPR(int id) {
    super(id);
  }

  public COLVALEXPR(Scanner p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public SimpleNode jjtAccept(ScannerVisitor visitor, SimpleNode data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a15dfe043da1985ce1317f045a07ef60 (do not edit this line) */
