/* Generated By:JJTree: Do not edit this line. CONSTRAINTS.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class CONSTRAINTS extends SimpleNode {
  public CONSTRAINTS(int id) {
    super(id);
  }

  public CONSTRAINTS(Scanner p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public SimpleNode jjtAccept(ScannerVisitor visitor, SimpleNode data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f46a1b9beebe91ff2e56787b528b6686 (do not edit this line) */
