/* Generated By:JJTree: Do not edit this line. RULEOPT.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class RULEOPT extends SimpleNode {
  public RULEOPT(int id) {
    super(id);
  }

  public RULEOPT(Scanner p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public SimpleNode jjtAccept(ScannerVisitor visitor, SimpleNode data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=10c0bb1e2fb081eab65697ea752dd396 (do not edit this line) */
