/* Generated By:JJTree&JavaCC: Do not edit this line. ScannerConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ScannerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IMPORT = 4;
  /** RegularExpression Id. */
  int IN = 5;
  /** RegularExpression Id. */
  int MODEL = 6;
  /** RegularExpression Id. */
  int ANALYZE = 7;
  /** RegularExpression Id. */
  int WITH = 8;
  /** RegularExpression Id. */
  int ROW = 9;
  /** RegularExpression Id. */
  int COL = 10;
  /** RegularExpression Id. */
  int NOHEADERS = 11;
  /** RegularExpression Id. */
  int IDKEY = 12;
  /** RegularExpression Id. */
  int EOL = 13;
  /** RegularExpression Id. */
  int COMPARISON = 14;
  /** RegularExpression Id. */
  int EQUAL = 15;
  /** RegularExpression Id. */
  int DEFINERULE = 16;
  /** RegularExpression Id. */
  int IS = 17;
  /** RegularExpression Id. */
  int OR = 18;
  /** RegularExpression Id. */
  int AND = 19;
  /** RegularExpression Id. */
  int NOT = 20;
  /** RegularExpression Id. */
  int CONSTRAINT = 21;
  /** RegularExpression Id. */
  int MAXLENGTH = 22;
  /** RegularExpression Id. */
  int MINLENGTH = 23;
  /** RegularExpression Id. */
  int CONTAINS = 24;
  /** RegularExpression Id. */
  int COMMA = 25;
  /** RegularExpression Id. */
  int DASH = 26;
  /** RegularExpression Id. */
  int LPAREN = 27;
  /** RegularExpression Id. */
  int RPAREN = 28;
  /** RegularExpression Id. */
  int ARGSSTART = 29;
  /** RegularExpression Id. */
  int ARGSSTOP = 30;
  /** RegularExpression Id. */
  int INT = 31;
  /** RegularExpression Id. */
  int FLOAT = 32;
  /** RegularExpression Id. */
  int STRING = 33;
  /** RegularExpression Id. */
  int FILENAME = 34;
  /** RegularExpression Id. */
  int ID = 35;
  /** RegularExpression Id. */
  int COMMENT = 37;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "\"\\r\"",
    "\" \"",
    "\"IMPORT\"",
    "\"IN\"",
    "\"MODEL\"",
    "\"ANALYZE\"",
    "\"WITH\"",
    "\"ROW\"",
    "\"COL\"",
    "\"NOHEADERS\"",
    "\"ID\"",
    "\"\\n\"",
    "<COMPARISON>",
    "\"=\"",
    "\":\"",
    "\"IS\"",
    "\"OR\"",
    "\"AND\"",
    "\"NOT\"",
    "<CONSTRAINT>",
    "\"MAXLENGTH\"",
    "\"MINLENGTH\"",
    "\"CONTAINS\"",
    "\",\"",
    "\"-\"",
    "\"(\"",
    "\")\"",
    "\"BEGIN\"",
    "\"END\"",
    "<INT>",
    "<FLOAT>",
    "<STRING>",
    "<FILENAME>",
    "<ID>",
    "\"//\"",
    "\"//\"",
    "<token of kind 38>",
  };

}
