/* Generated By:JJTree&JavaCC: Do not edit this line. ScannerConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ScannerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IMPORT = 4;
  /** RegularExpression Id. */
  int IN = 5;
  /** RegularExpression Id. */
  int MODEL = 6;
  /** RegularExpression Id. */
  int ANALYZE = 7;
  /** RegularExpression Id. */
  int WITH = 8;
  /** RegularExpression Id. */
  int ROW = 9;
  /** RegularExpression Id. */
  int COL = 10;
  /** RegularExpression Id. */
  int NOHEADERS = 11;
  /** RegularExpression Id. */
  int IDKEY = 12;
  /** RegularExpression Id. */
  int TO = 13;
  /** RegularExpression Id. */
  int EOL = 14;
  /** RegularExpression Id. */
  int COMPARISON = 15;
  /** RegularExpression Id. */
  int EQUAL = 16;
  /** RegularExpression Id. */
  int DEFINERULE = 17;
  /** RegularExpression Id. */
  int IS = 18;
  /** RegularExpression Id. */
  int OR = 19;
  /** RegularExpression Id. */
  int AND = 20;
  /** RegularExpression Id. */
  int NOT = 21;
  /** RegularExpression Id. */
  int CONSTRAINT = 22;
  /** RegularExpression Id. */
  int CONTAINS = 23;
  /** RegularExpression Id. */
  int COMMA = 24;
  /** RegularExpression Id. */
  int LPAREN = 25;
  /** RegularExpression Id. */
  int RPAREN = 26;
  /** RegularExpression Id. */
  int ARGSSTART = 27;
  /** RegularExpression Id. */
  int ARGSSTOP = 28;
  /** RegularExpression Id. */
  int INT = 29;
  /** RegularExpression Id. */
  int FLOAT = 30;
  /** RegularExpression Id. */
  int STRING = 31;
  /** RegularExpression Id. */
  int FILENAME = 32;
  /** RegularExpression Id. */
  int ID = 33;
  /** RegularExpression Id. */
  int COMMENT = 35;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "\"\\r\"",
    "\" \"",
    "\"IMPORT\"",
    "\"IN\"",
    "\"MODEL\"",
    "\"ANALYZE\"",
    "\"WITH\"",
    "\"ROW\"",
    "\"COL\"",
    "\"NOHEADERS\"",
    "\"ID\"",
    "\"TO\"",
    "\"\\n\"",
    "<COMPARISON>",
    "\"=\"",
    "\":\"",
    "\"IS\"",
    "\"OR\"",
    "\"AND\"",
    "\"NOT\"",
    "<CONSTRAINT>",
    "\"CONTAINS\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"BEGIN\"",
    "\"END\"",
    "<INT>",
    "<FLOAT>",
    "<STRING>",
    "<FILENAME>",
    "<ID>",
    "\"//\"",
    "\"//\"",
    "<token of kind 36>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
  };

}
