/* Generated By:JavaCC: Do not edit this line. ScannerTreeConstants.java Version 5.0 */
public interface ScannerTreeConstants
{
  public int JJTPROG = 0;
  public int JJTIMPORT = 1;
  public int JJTOPTIONS = 2;
  public int JJTFLNM = 3;
  public int JJTNOHEADERS = 4;
  public int JJTMODEL = 5;
  public int JJTVOID = 6;
  public int JJTRULE = 7;
  public int JJTPARTRULE = 8;
  public int JJTOR = 9;
  public int JJTAND = 10;
  public int JJTVALEXPR = 11;
  public int JJTTYPES = 12;
  public int JJTADD = 13;
  public int JJTMULT = 14;
  public int JJTNOT = 15;
  public int JJTCONTAINS = 16;
  public int JJTCONSTRAINTS = 17;
  public int JJTSTRING = 18;
  public int JJTINTEGER = 19;
  public int JJTFLOATY = 20;
  public int JJTANALYZE = 21;
  public int JJTRULES = 22;
  public int JJTROWS = 23;
  public int JJTCOLS = 24;
  public int JJTRANGE = 25;
  public int JJTIDEN = 26;


  public String[] jjtNodeName = {
    "PROG",
    "IMPORT",
    "OPTIONS",
    "FLNM",
    "NOHEADERS",
    "MODEL",
    "void",
    "RULE",
    "PARTRULE",
    "OR",
    "AND",
    "VALEXPR",
    "TYPES",
    "ADD",
    "MULT",
    "NOT",
    "CONTAINS",
    "CONSTRAINTS",
    "STRING",
    "INTEGER",
    "FLOATY",
    "ANALYZE",
    "RULES",
    "ROWS",
    "COLS",
    "RANGE",
    "IDEN",
  };
}
/* JavaCC - OriginalChecksum=afd234003f1e99ab8f4924f4d120e6fa (do not edit this line) */
