/* Generated By:JavaCC: Do not edit this line. ScannerTreeConstants.java Version 5.0 */
public interface ScannerTreeConstants
{
  public int JJTPROG = 0;
  public int JJTIMPORT = 1;
  public int JJTIMOPTIONS = 2;
  public int JJTFLNM = 3;
  public int JJTMODEL = 4;
  public int JJTVOID = 5;
  public int JJTRULE = 6;
  public int JJTOR = 7;
  public int JJTAND = 8;
  public int JJTVALEXPR = 9;
  public int JJTREGEX = 10;
  public int JJTREGOREXPR = 11;
  public int JJTREGEXPR = 12;
  public int JJTLENGTH = 13;
  public int JJTCONSTRAINTS = 14;
  public int JJTSTRING = 15;
  public int JJTINTEGER = 16;
  public int JJTFLOATY = 17;
  public int JJTANALYZE = 18;
  public int JJTANOPTIONS = 19;
  public int JJTRULEOPT = 20;
  public int JJTROWOPT = 21;
  public int JJTCOLOPT = 22;
  public int JJTROWS = 23;
  public int JJTCOLS = 24;
  public int JJTINDEX = 25;
  public int JJTIDEN = 26;


  public String[] jjtNodeName = {
    "PROG",
    "IMPORT",
    "IMOPTIONS",
    "FLNM",
    "MODEL",
    "void",
    "RULE",
    "OR",
    "AND",
    "VALEXPR",
    "REGEX",
    "REGOREXPR",
    "REGEXPR",
    "LENGTH",
    "CONSTRAINTS",
    "STRING",
    "INTEGER",
    "FLOATY",
    "ANALYZE",
    "ANOPTIONS",
    "RULEOPT",
    "ROWOPT",
    "COLOPT",
    "ROWS",
    "COLS",
    "INDEX",
    "IDEN",
  };
}
/* JavaCC - OriginalChecksum=53ae74c0d1c2c95de3e6dd29ae145b4f (do not edit this line) */
