/* Generated By:JavaCC: Do not edit this line. ScannerTreeConstants.java Version 5.0 */
public interface ScannerTreeConstants
{
  public int JJTPROG = 0;
  public int JJTIMPORT = 1;
  public int JJTIMPOPTIONS = 2;
  public int JJTFLNM = 3;
  public int JJTNOHEADERS = 4;
  public int JJTMODEL = 5;
  public int JJTVOID = 6;
  public int JJTCOLRULE = 7;
  public int JJTPARTRULE = 8;
  public int JJTOR = 9;
  public int JJTAND = 10;
  public int JJTCOLVALEXPR = 11;
  public int JJTWHERE = 12;
  public int JJTSACD = 13;
  public int JJTADD = 14;
  public int JJTMULT = 15;
  public int JJTRULE = 16;
  public int JJTVALEXPR = 17;
  public int JJTCONSTRAINTS = 18;
  public int JJTSTRING = 19;
  public int JJTINTEGER = 20;
  public int JJTFLOATY = 21;
  public int JJTANALYZE = 22;
  public int JJTANLZOPTIONS = 23;
  public int JJTRULEOPT = 24;
  public int JJTROWS = 25;
  public int JJTCOLS = 26;
  public int JJTRANGE = 27;
  public int JJTIDEN = 28;


  public String[] jjtNodeName = {
    "PROG",
    "IMPORT",
    "IMPOPTIONS",
    "FLNM",
    "NOHEADERS",
    "MODEL",
    "void",
    "COLRULE",
    "PARTRULE",
    "OR",
    "AND",
    "COLVALEXPR",
    "WHERE",
    "SACD",
    "ADD",
    "MULT",
    "RULE",
    "VALEXPR",
    "CONSTRAINTS",
    "STRING",
    "INTEGER",
    "FLOATY",
    "ANALYZE",
    "ANLZOPTIONS",
    "RULEOPT",
    "ROWS",
    "COLS",
    "RANGE",
    "IDEN",
  };
}
/* JavaCC - OriginalChecksum=aa3ef05b4899fbda38d66df092a657b5 (do not edit this line) */
