/* Generated By:JavaCC: Do not edit this line. ScannerVisitor.java Version 5.0 */
public interface ScannerVisitor
{
  public SimpleNode visit(SimpleNode node, SimpleNode data);
  public SimpleNode visit(PROG node, SimpleNode data);
  public SimpleNode visit(IMPORT node, SimpleNode data);
  public SimpleNode visit(IMPOPTIONS node, SimpleNode data);
  public SimpleNode visit(FLNM node, SimpleNode data);
  public SimpleNode visit(NOHEADERS node, SimpleNode data);
  public SimpleNode visit(MODEL node, SimpleNode data);
  public SimpleNode visit(COLRULE node, SimpleNode data);
  public SimpleNode visit(PARTRULE node, SimpleNode data);
  public SimpleNode visit(OR node, SimpleNode data);
  public SimpleNode visit(AND node, SimpleNode data);
  public SimpleNode visit(COLVALEXPR node, SimpleNode data);
  public SimpleNode visit(WHERE node, SimpleNode data);
  public SimpleNode visit(SACD node, SimpleNode data);
  public SimpleNode visit(ADD node, SimpleNode data);
  public SimpleNode visit(MULT node, SimpleNode data);
  public SimpleNode visit(RULE node, SimpleNode data);
  public SimpleNode visit(VALEXPR node, SimpleNode data);
  public SimpleNode visit(CONSTRAINTS node, SimpleNode data);
  public SimpleNode visit(STRING node, SimpleNode data);
  public SimpleNode visit(INTEGER node, SimpleNode data);
  public SimpleNode visit(FLOATY node, SimpleNode data);
  public SimpleNode visit(ANALYZE node, SimpleNode data);
  public SimpleNode visit(ANLZOPTIONS node, SimpleNode data);
  public SimpleNode visit(RULEOPT node, SimpleNode data);
  public SimpleNode visit(ROWS node, SimpleNode data);
  public SimpleNode visit(COLS node, SimpleNode data);
  public SimpleNode visit(RANGE node, SimpleNode data);
  public SimpleNode visit(IDEN node, SimpleNode data);
}
/* JavaCC - OriginalChecksum=7471eaf91e07543490062a4b4faf774e (do not edit this line) */
