/* Generated By:JJTree: Do not edit this line. INTEGER.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package src.classes.scanner;

public
class INTEGER extends SimpleNode {
  public INTEGER(int id) {
    super(id);
  }

  public INTEGER(Scanner p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public SimpleNode jjtAccept(ScannerVisitor visitor, SimpleNode data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=aaa3dafe2dd2cb76e1b9dfd6b8bd55d8 (do not edit this line) */
