/* Generated By:JJTree: Do not edit this line. ANLZOPTIONS.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package src;

public
class ANLZOPTIONS extends SimpleNode {
  public ANLZOPTIONS(int id) {
    super(id);
  }

  public ANLZOPTIONS(Scanner p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public SimpleNode jjtAccept(ScannerVisitor visitor, SimpleNode data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e7ed0c36830fd33724a9e326436d51e1 (do not edit this line) */
