/* Generated By:JJTree: Do not edit this line. COLPARTRULE.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package src;

public
class COLPARTRULE extends SimpleNode {
  public COLPARTRULE(int id) {
    super(id);
  }

  public COLPARTRULE(Scanner p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public SimpleNode jjtAccept(ScannerVisitor visitor, SimpleNode data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6ff0c54d8c02de6818f7d44c96c20c56 (do not edit this line) */
