/* Generated By:JJTree: Do not edit this line. CONSTRAINTS.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package src;

public
class CONSTRAINTS extends SimpleNode {
  public CONSTRAINTS(int id) {
    super(id);
  }

  public CONSTRAINTS(Scanner p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public SimpleNode jjtAccept(ScannerVisitor visitor, SimpleNode data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=786f3001833f0092a6467f04b08fab0e (do not edit this line) */
