/* Generated By:JJTree: Do not edit this line. DIVIDE.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package src;
public
class DIVIDE extends SimpleNode {
  public DIVIDE(int id) {
    super(id);
  }

  public DIVIDE(Scanner p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public SimpleNode jjtAccept(ScannerVisitor visitor, SimpleNode data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6ef0e493e472cd0ddfa8a096893f1ea6 (do not edit this line) */
