/* Generated By:JJTree: Do not edit this line. FLOATY.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package src;

public
class FLOATY extends SimpleNode {
  public FLOATY(int id) {
    super(id);
  }

  public FLOATY(Scanner p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public SimpleNode jjtAccept(ScannerVisitor visitor, SimpleNode data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b133063eda9dfe1742727cec6a4c6459 (do not edit this line) */
