/* Generated By:JJTree: Do not edit this line. IMPOPTIONS.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package src;

public
class IMPOPTIONS extends SimpleNode {
  public IMPOPTIONS(int id) {
    super(id);
  }

  public IMPOPTIONS(Scanner p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public SimpleNode jjtAccept(ScannerVisitor visitor, SimpleNode data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=249701cbfd08fbae12ce56c8988a9a78 (do not edit this line) */
