/* Generated By:JavaCC: Do not edit this line. ScannerTreeConstants.java Version 5.0 */
package src;

public interface ScannerTreeConstants
{
  public int JJTPROG = 0;
  public int JJTIMPORT = 1;
  public int JJTIMPOPTIONS = 2;
  public int JJTFLNM = 3;
  public int JJTNOHEADERS = 4;
  public int JJTMODEL = 5;
  public int JJTVOID = 6;
  public int JJTCOLRULE = 7;
  public int JJTCOLPARTRULE = 8;
  public int JJTCOLOR = 9;
  public int JJTCOLAND = 10;
  public int JJTCOLVALEXPR = 11;
  public int JJTWHERE = 12;
  public int JJTSACD = 13;
  public int JJTRULE = 14;
  public int JJTPARTRULE = 15;
  public int JJTOR = 16;
  public int JJTAND = 17;
  public int JJTVALEXPR = 18;
  public int JJTCONSTRAINTS = 19;
  public int JJTSTRING = 20;
  public int JJTINTEGER = 21;
  public int JJTFLOATY = 22;
  public int JJTANALYZE = 23;
  public int JJTANLZOPTIONS = 24;
  public int JJTRULEOPT = 25;
  public int JJTROWS = 26;
  public int JJTCOLS = 27;
  public int JJTRANGE = 28;
  public int JJTIDEN = 29;
  public int JJTMULT = 30;
  public int JJTADD = 31;


  public String[] jjtNodeName = {
    "PROG",
    "IMPORT",
    "IMPOPTIONS",
    "FLNM",
    "NOHEADERS",
    "MODEL",
    "void",
    "COLRULE",
    "COLPARTRULE",
    "COLOR",
    "COLAND",
    "COLVALEXPR",
    "WHERE",
    "SACD",
    "RULE",
    "PARTRULE",
    "OR",
    "AND",
    "VALEXPR",
    "CONSTRAINTS",
    "STRING",
    "INTEGER",
    "FLOATY",
    "ANALYZE",
    "ANLZOPTIONS",
    "RULEOPT",
    "ROWS",
    "COLS",
    "RANGE",
    "IDEN",
    "MULT",
    "ADD",
  };
}
/* JavaCC - OriginalChecksum=59bd1f4e305d1fd78b9a2c0660f99ce2 (do not edit this line) */
