/* Generated By:JJTree: Do not edit this line. ASTANALYZE.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTANALYZE extends SimpleNode {
  public ASTANALYZE(int id) {
    super(id);
  }

  public ASTANALYZE(Scanner p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ScannerVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=56eae314534ec9525723b173249e0e49 (do not edit this line) */
