/* Generated By:JJTree: Do not edit this line. ASTCONSTRAINTS.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package SyntaxAnalysis.TreeFiles;

public class ASTCONSTRAINTS extends SimpleNode {
  public ASTCONSTRAINTS(int id) {
    super(id);
  }

  public ASTCONSTRAINTS(Scanner p, int id) {
    super(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(ScannerVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/*
 * JavaCC - OriginalChecksum=bb05bcb76448323e1ec156f8adaae4b6 (do not edit this
 * line)
 */
