/* Generated By:JJTree: Do not edit this line. ASTFLOATY.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package SyntaxAnalysis.TreeFiles;

public class ASTFLOATY extends SimpleNode {
  public ASTFLOATY(int id) {
    super(id);
  }

  public ASTFLOATY(Scanner p, int id) {
    super(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(ScannerVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/*
 * JavaCC - OriginalChecksum=238db2e91e064d96fcc0a5b609ae52ca (do not edit this
 * line)
 */
