/* Generated By:JJTree: Do not edit this line. ASTIDEN.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package SyntaxAnalysis.TreeFiles;

public class ASTIDEN extends SimpleNode {

  public int type;

  public ASTIDEN(int id) {
    super(id);
  }

  public ASTIDEN(Scanner p, int id) {
    super(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(ScannerVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/*
 * JavaCC - OriginalChecksum=106161ebc3336b9a2d41467070f40ded (do not edit this
 * line)
 */
