/* Generated By:JJTree: Do not edit this line. ASTINTEGER.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package SyntaxAnalysis.TreeFiles;

public class ASTINTEGER extends SimpleNode {
  public ASTINTEGER(int id) {
    super(id);
  }

  public ASTINTEGER(Scanner p, int id) {
    super(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(ScannerVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/*
 * JavaCC - OriginalChecksum=4b9389b157add121cb0f36ce6ad75c4a (do not edit this
 * line)
 */
