/* Generated By:JJTree: Do not edit this line. ASTOR.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package SyntaxAnalysis.TreeFiles;

public class ASTOR extends SimpleNode {
  public ASTOR(int id) {
    super(id);
  }

  public ASTOR(Scanner p, int id) {
    super(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(ScannerVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/*
 * JavaCC - OriginalChecksum=f1451caf2809882792c9682143dfc3e1 (do not edit this
 * line)
 */
