/* Generated By:JJTree: Do not edit this line. ASTTYPES.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package SyntaxAnalysis.TreeFiles;

public class ASTTYPES extends SimpleNode {
  public ASTTYPES(int id) {
    super(id);
  }

  public ASTTYPES(Scanner p, int id) {
    super(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(ScannerVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/*
 * JavaCC - OriginalChecksum=ea299e7a6a8fe145317080bfe9a69d05 (do not edit this
 * line)
 */
