/* Generated By:JJTree: Do not edit this line. ASTVALEXPR.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTVALEXPR extends SimpleNode {
  public ASTVALEXPR(int id) {
    super(id);
  }

  public ASTVALEXPR(Scanner p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ScannerVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e038e30ce49cf67b7dce4c7d24f108ce (do not edit this line) */
