/* Generated By:JavaCC: Do not edit this line. ScannerTreeConstants.java Version 5.0 */
public interface ScannerTreeConstants
{
  public int JJTPROG = 0;
  public int JJTIMPORT = 1;
  public int JJTFLNM = 2;
  public int JJTMODEL = 3;
  public int JJTVOID = 4;
  public int JJTRULE = 5;
  public int JJTOR = 6;
  public int JJTAND = 7;
  public int JJTVALEXPR = 8;
  public int JJTCONSTRAINTS = 9;
  public int JJTTYPES = 10;
  public int JJTINTEGER = 11;
  public int JJTFLOATY = 12;
  public int JJTANALYZE = 13;
  public int JJTIDEN = 14;


  public String[] jjtNodeName = {
    "PROG",
    "IMPORT",
    "FLNM",
    "MODEL",
    "void",
    "RULE",
    "OR",
    "AND",
    "VALEXPR",
    "CONSTRAINTS",
    "TYPES",
    "INTEGER",
    "FLOATY",
    "ANALYZE",
    "IDEN",
  };
}
/* JavaCC - OriginalChecksum=945c8378dda540603dbf513a8af4bcdc (do not edit this line) */
