/* Generated By:JJTree&JavaCC: Do not edit this line. ScannerConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
package SyntaxAnalysis.TreeFiles;

public interface ScannerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IMPORT = 4;
  /** RegularExpression Id. */
  int IN = 5;
  /** RegularExpression Id. */
  int MODEL = 6;
  /** RegularExpression Id. */
  int BLOCKSTART = 7;
  /** RegularExpression Id. */
  int BLOCKSTOP = 8;
  /** RegularExpression Id. */
  int ANALYZE = 9;
  /** RegularExpression Id. */
  int WITH = 10;
  /** RegularExpression Id. */
  int EOL = 11;
  /** RegularExpression Id. */
  int COMPARISON = 12;
  /** RegularExpression Id. */
  int EQUAL = 13;
  /** RegularExpression Id. */
  int DEFINERULE = 14;
  /** RegularExpression Id. */
  int IS = 15;
  /** RegularExpression Id. */
  int OR = 16;
  /** RegularExpression Id. */
  int AND = 17;
  /** RegularExpression Id. */
  int CONSTRAINT = 18;
  /** RegularExpression Id. */
  int INT = 19;
  /** RegularExpression Id. */
  int FLOAT = 20;
  /** RegularExpression Id. */
  int STRING = 21;
  /** RegularExpression Id. */
  int FILENAME = 22;
  /** RegularExpression Id. */
  int ID = 23;
  /** RegularExpression Id. */
  int COMMENT = 25;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = { "<EOF>", "\"\\t\"", "\"\\r\"", "\" \"", "\"IMPORT\"", "\"IN\"", "\"MODEL\"", "\"BEGIN\"",
      "\"END\"", "\"ANALYZE\"", "\"WITH\"", "\"\\n\"", "<COMPARISON>", "\"=\"", "\":\"", "\"IS\"", "\"OR\"", "\"AND\"",
      "<CONSTRAINT>", "<INT>", "<FLOAT>", "<STRING>", "<FILENAME>", "<ID>", "\"//\"", "\"//\"", "<token of kind 26>",
      "\"(\"", "\")\"", };

}
