/* Generated By:JavaCC: Do not edit this line. ScannerVisitor.java Version 5.0 */
public interface ScannerVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTPROG node, Object data);
  public Object visit(ASTIMPORT node, Object data);
  public Object visit(ASTFLNM node, Object data);
  public Object visit(ASTMODEL node, Object data);
  public Object visit(ASTRULE node, Object data);
  public Object visit(ASTOR node, Object data);
  public Object visit(ASTAND node, Object data);
  public Object visit(ASTVALEXPR node, Object data);
  public Object visit(ASTCONSTRAINTS node, Object data);
  public Object visit(ASTTYPES node, Object data);
  public Object visit(ASTINTEGER node, Object data);
  public Object visit(ASTFLOATY node, Object data);
  public Object visit(ASTANALYZE node, Object data);
  public Object visit(ASTIDEN node, Object data);
}
/* JavaCC - OriginalChecksum=b7e5d146e77c7b37a06c5cef3c39f1ed (do not edit this line) */
